### ISSUE TITLE
Good work! 🌟🌟🌟🌟🌟

### ISSUE THREAD

**Issue by missKatiaPunter** [Caitlin1306/my_first_notebook#2]
Excellent work, Caitlin.

A couple of things that have not worked for you yet.

You should try using back-ticks to make neater code blocks again. I know they are fiddly but you get used to them. That is what a code block should look like:

```
name = input("what is your name?")
print("Hello " + name)
men_lifting_weights_emojis = int(input("How many men lifting weights emojis would you like?"))
print("🏋️" * men_lifting_weights_emojis)
```

**Comment by missKatiaPunter** [comment]
If I were you I would make sure `I` spelled I as a capital. You can use a Google doc or a Grammarly app to draft the text of your README first.

**Comment by missKatiaPunter** [comment]
Finally, I think you meant to add the last section to the other repository.

A README explains the project. It should be relevant only to the code that is in the project and not to the code in the other project.

**Comment by Caitlin1306** [comment]
Hi Katia, I believe I have now done all my changes.
https://github.com/Caitlin1306/turtle_task/blob/main/README.md
https://github.com/Caitlin1306/my_first_notebook/blob/main/README.md
